### ISSUE TITLE
Aggiungere registrazione newsletter

### ISSUE THREAD

**Issue by v1proxy** [coompany/onggi-tracker#43]
Aggiungere registrazione alla newsletter in home (campo inserimento mail e conferma)

La newsletter verra gestita internamente da ONGGI attraverso Mailchimp

**Comment by acidghost** [comment]
@v1proxy  Salvo i dati in una tabella e poi la mostro in una nuova pagina admin?

**Comment by v1proxy** [comment]
Si perchè per come è stata pensata la registrazione newsletter non è associata al database utenti

**Comment by acidghost** [comment]
Inserisco un box in home, sotto il manifesto, con titolo (eg "Iscriviti alla newsletter") e sotto direttamente il controllo per inserire la mail e sotto il bottone per confermare; tutto centrato.

Da admin, aggiungo una nuova navigazione principale "newsletter" e dentro una tabella con id riga, email e data di inserimento.

Va bene?

**Comment by v1proxy** [comment]
Si va bene
