### ISSUE TITLE
Aggiungere disclaimer privacy

### ISSUE THREAD

**Issue by v1proxy** [coompany/onggi-tracker#44]
Aggiungere disclaimer privacy in fase di registrazione secondo testo fornito da ONGGI

**Comment by acidghost** [comment]
![screenshot-localhost_4200-2019 09 26-19_45_23](https://user-images.githubusercontent.com/1787979/65711950-45aa0f80-e096-11e9-9a59-d9fa59b0ffad.png)
@v1proxy  Va bene così o serve un link ad una pagina separata? Poi non ricordo, non devo salvare nulla della spunta nel database, giusto?

**Comment by v1proxy** [comment]
Serve un link ad una pagina separata. Non c`e un on-off, semplicemente un disclaimer "registrando accetti di aderire alla normativa blablabla (non abbiamo ancora il testo). Nel disclaimer ci sara il link al testo della normativa

**Comment by v1proxy** [comment]
Nel database non dovrai salvare niente, perche appunto e considerato che ogni iscritto abbia aderito alla normativa
